### ISSUE TITLE
utahfs-client first impression and errors

### ISSUE THREAD

**Issue by agowa338** [cloudflare/utahfs#10]
The documentation mentions a go get command for installing the utahfs client,  but if fails to install at least on ArchLinux because of go-sqlite3
```
[user@archBook ~]$ go get github.com/cloudflare/utahfs/cmd/utahfs-client
# github.com/cloudflare/utahfs/vendor/github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:123303:10: warning: function may return address of local variable [-Wreturn-local-addr]
123303 |   return pNew;
       |          ^~~~
sqlite3-binding.c:123263:10: note: declared here
123263 |   Select standin;
       |          ^~~~~~~
```

Can this error safely be ignored? It creates a binary within `~/go/bin`, but it appears to run unstable, it crashed right after I tried to copy a file into the mountpoint.
```
[user@archBook bin]$ cd /tmp/utahfs/
[user@archBook utahfs]$ /home/user/go/bin/utahfs-client -cfg ./utahfs.yaml -mount ./
mount/       utahfs.yaml  
[user@archBook utahfs]$ /home/user/go/bin/utahfs-client -cfg ./utahfs.yaml -mount ./mount/
2020/06/11 22:19:15 integrity.go:55: integrity: local pin file not found, will accept whatever remote storage returns
2020/06/11 22:19:16 main.go:72: filesystem successfully mounted
fuse: 2020/06/11 22:20:03 connection.go:486: *fuseops.GetXattrOp error: function not implemented
2020/06/11 22:21:26 filesystem.go:665: runtime error: slice bounds out of range [:147456] with capacity 135088
2020/06/11 22:21:26 filesystem.go:666: goroutine 35076 [running]:
runtime/debug.Stack(0xc01679dc00, 0x1, 0x1)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/cloudflare/utahfs.(*filesystem).synchronize.func1()
        /home/user/go/src/github.com/cloudflare/utahfs/filesystem.go:666 +0x13d
panic(0xe59e00, 0xc05cb0d980)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/cloudflare/utahfs.checkForChanges(0xc054c81130, 0xc05747f4a0, 0xc05747f4d0, 0x1)
        /home/user/go/src/github.com/cloudflare/utahfs/archive.go:61 +0x29c
github.com/cloudflare/utahfs.(*filesystem).writeFile(0xc003751980, 0x1094900, 0xc05747f4d0, 0xc05747f4a0, 0xc00cede001, 0x0, 0x0)
        /home/user/go/src/github.com/cloudflare/utahfs/filesystem.go:545 +0x2a2
github.com/cloudflare/utahfs.archive.WriteFile(0xc003751980, 0x1094900, 0xc05747f4d0, 0xc05747f4a0, 0xc0584840c0, 0x0)
        /home/user/go/src/github.com/cloudflare/utahfs/archive.go:43 +0x4e
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc00000f320, 0xc014c7c0d0, 0x1094900, 0xc05747f4d0, 0xd1ac20, 0xc05747f4a0)
        /home/user/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:193 +0x325
created by github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/user/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x182

panic: runtime error: slice bounds out of range [:147456] with capacity 135088 [recovered]
        panic: runtime error: slice bounds out of range [:147456] with capacity 135088

goroutine 35076 [running]:
github.com/cloudflare/utahfs.(*filesystem).synchronize.func1()
        /home/user/go/src/github.com/cloudflare/utahfs/filesystem.go:667 +0x1d5
panic(0xe59e00, 0xc05cb0d980)
        /usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/cloudflare/utahfs.checkForChanges(0xc054c81130, 0xc05747f4a0, 0xc05747f4d0, 0x1)
        /home/user/go/src/github.com/cloudflare/utahfs/archive.go:61 +0x29c
github.com/cloudflare/utahfs.(*filesystem).writeFile(0xc003751980, 0x1094900, 0xc05747f4d0, 0xc05747f4a0, 0xc00cede001, 0x0, 0x0)
        /home/user/go/src/github.com/cloudflare/utahfs/filesystem.go:545 +0x2a2
github.com/cloudflare/utahfs.archive.WriteFile(0xc003751980, 0x1094900, 0xc05747f4d0, 0xc05747f4a0, 0xc0584840c0, 0x0)
        /home/user/go/src/github.com/cloudflare/utahfs/archive.go:43 +0x4e
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc00000f320, 0xc014c7c0d0, 0x1094900, 0xc05747f4d0, 0xd1ac20, 0xc05747f4a0)
        /home/user/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:193 +0x325
created by github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
        /home/user/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseutil/file_system.go:121 +0x182
[user@archBook utahfs]$ /home/user/go/bin/utahfs-client -cfg ./utahfs.yaml -mount ./mount/
2020/06/11 22:24:06 main.go:67: Statting mount point: stat /tmp/utahfs/mount: transport endpoint is not connected
[user@archBook utahfs]$ ls
ls: cannot access 'mount': Transport endpoint is not connected
mount  utahfs.yaml
[user@archBook utahfs]$ cd mo
bash: cd: mo: No such file or directory
[user@archBook utahfs]$ ls -la
ls: cannot access 'mount': Transport endpoint is not connected
total 4
drwxr-xr-x  4 user users 100 Jun 11 22:19 .
drwxrwxrwt 22 root root  500 Jun 11 22:19 ..
drwxr--r--  2 user users 120 Jun 11 22:21 .utahfs
d?????????  ? ?    ?       ?            ? mount
-rw-r--r--  1 user users 397 Jun 11 22:09 utahfs.yaml
[user@archBook utahfs]$ pwd
/tmp/utahfs

```
and after rebooting the device it does not even allow to "cd" into the mount directory
```
[user@archBook utahfs]$ /home/user/go/bin/utahfs-client -cfg ./utahfs.yaml -mount ./mount/
2020/06/11 22:32:24 main.go:72: filesystem successfully mounted
fuse: 2020/06/11 22:32:30 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:30 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:30 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:31 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:31 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:31 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
fuse: 2020/06/11 22:32:32 connection.go:486: *fuseops.GetInodeAttributesOp error: integrity: block does not equal expected value
```
after deleting the whole content of the bucket and also the hidden ".utahfs" folder it worked the 2nd time. But because of this complete data loss I do not think it's production ready yet.

Than I tried to copy a large file 50 GB into the mountpoint using cp after 5 minutes ist still had only uploaded a few MB, therefore I canceled the cp using CTRL+C and than the whole Terminal was unresponsable and KDE asked me if I want to kill it. There might not be anything utahfs could to, as this is most likely an issue within cp getting stuck on the io operation even though it has been killed using CTRL+C, but I think it is notable.

Now I tried it again but with more verbosity turned on to see what's happening, but this time it got stuck and froze the terminal even without pressing anything, completely on it's own.
![image](https://user-images.githubusercontent.com/2544867/84451344-1bfc3d00-ac53-11ea-9bff-111f115ab3b6.png)
![image](https://user-images.githubusercontent.com/2544867/84451508-8ca35980-ac53-11ea-8218-d9b75a7f7444.png)

**Comment by Bren2010** [comment]
Ok, so there's a lot here.

1. I think it's fine to ignore the compile warning.

2. The panic you reported was a genuine bug in the archive mode, which has been fixed.

3. This error: `main.go:67: Statting mount point: stat /tmp/utahfs/mount: transport endpoint is not connected` and the following `Transport endpoint is not connected` errors are a result of UtahFS crashing the first time and not unmounting properly. So what you could've done here is "sudo umount ./utahfs" to force the FS to unmount.

4. I don't fully know yet what's caused the `integrity: block does not equal expected value` error or your performance issues.

**Comment by Bren2010** [comment]
I also wanted to say, thank you so much for writing all this up!

**Comment by Bren2010** [comment]
Going to close this for now. If you decide to try UtahFS again and run into more issues, please don't hesitate to open another ticket
