### ISSUE TITLE
setup / build instructions on raspberry pi don't work

### ISSUE THREAD

**Issue by AndrewBudd** [cloudflare/utahfs#14]
go get runs, but no binary artifacts are produced

```
pi@raspberrypi:~ $ go get -v github.com/cloudflare/utahfs/cmd/utahfs-client
github.com/cloudflare/utahfs (download)
created GOPATH=/home/pi/go; see 'go help gopath'
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/grpclog
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/serviceconfig
github.com/cloudflare/utahfs/vendor/github.com/golang/groupcache/lru
github.com/cloudflare/utahfs/cache
github.com/cloudflare/utahfs/vendor/golang.org/x/net/internal/timeseries
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/backoff
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/grpclog
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/credentials/internal
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/proto
github.com/cloudflare/utahfs/vendor/golang.org/x/net/trace
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/connectivity
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/metadata
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/attributes
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/grpcrand
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/codes
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/encoding
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/backoff
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/balancerload
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/buffer
github.com/cloudflare/utahfs/vendor/golang.org/x/sys/unix
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/envconfig
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/grpcsync
github.com/cloudflare/utahfs/vendor/golang.org/x/text/transform
github.com/cloudflare/utahfs/vendor/golang.org/x/text/unicode/bidi
github.com/cloudflare/utahfs/vendor/golang.org/x/text/unicode/norm
github.com/cloudflare/utahfs/vendor/golang.org/x/text/secure/bidirule
github.com/cloudflare/utahfs/vendor/golang.org/x/net/http2/hpack
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/keepalive
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/stats
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/tap
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/naming
github.com/cloudflare/utahfs/vendor/golang.org/x/net/idna
github.com/cloudflare/utahfs/vendor/google.golang.org/api/internal/third_party/uritemplates
github.com/cloudflare/utahfs/vendor/google.golang.org/api/googleapi
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/syscall
github.com/cloudflare/utahfs/vendor/golang.org/x/net/http/httpguts
github.com/cloudflare/utahfs/vendor/golang.org/x/net/http2
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/internal/optional
github.com/cloudflare/utahfs/vendor/go.opencensus.io
github.com/cloudflare/utahfs/vendor/go.opencensus.io/internal
github.com/cloudflare/utahfs/vendor/go.opencensus.io/trace/internal
github.com/cloudflare/utahfs/vendor/go.opencensus.io/trace/tracestate
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/internal/version
github.com/cloudflare/utahfs/vendor/go.opencensus.io/trace
github.com/cloudflare/utahfs/vendor/google.golang.org/api/iterator
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/credentials
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/encoding/proto
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/ptypes/any
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/resolver
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/ptypes/duration
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/ptypes/timestamp
github.com/cloudflare/utahfs/vendor/google.golang.org/genproto/googleapis/rpc/status
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/balancer
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/ptypes
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/balancer/base
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/status
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/channelz
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/balancer/roundrobin
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/grpcutil
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/resolver/dns
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/binarylog
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/resolver/passthrough
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/peer
github.com/cloudflare/utahfs/vendor/github.com/golang/protobuf/protoc-gen-go/descriptor
github.com/cloudflare/utahfs/vendor/google.golang.org/genproto/googleapis/type/expr
github.com/cloudflare/utahfs/vendor/google.golang.org/genproto/googleapis/rpc/code
github.com/cloudflare/utahfs/vendor/golang.org/x/net/context/ctxhttp
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/internal/trace
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc/internal/transport
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/compute/metadata
github.com/cloudflare/utahfs/vendor/golang.org/x/oauth2/internal
github.com/cloudflare/utahfs/vendor/golang.org/x/oauth2/jws
github.com/cloudflare/utahfs/vendor/google.golang.org/genproto/googleapis/api/annotations
github.com/cloudflare/utahfs/vendor/go.opencensus.io/trace/propagation
github.com/cloudflare/utahfs/vendor/go.opencensus.io/plugin/ochttp/propagation/b3
github.com/cloudflare/utahfs/vendor/go.opencensus.io/resource
github.com/cloudflare/utahfs/vendor/go.opencensus.io/tag
github.com/cloudflare/utahfs/vendor/golang.org/x/oauth2
github.com/cloudflare/utahfs/vendor/go.opencensus.io/metric/metricdata
github.com/cloudflare/utahfs/vendor/go.opencensus.io/internal/tagencoding
github.com/cloudflare/utahfs/vendor/go.opencensus.io/metric/metricproducer
github.com/cloudflare/utahfs/vendor/golang.org/x/oauth2/jwt
github.com/cloudflare/utahfs/vendor/google.golang.org/api/googleapi/transport
github.com/cloudflare/utahfs/vendor/google.golang.org/grpc
github.com/cloudflare/utahfs/vendor/google.golang.org/api/transport/cert
github.com/cloudflare/utahfs/vendor/golang.org/x/oauth2/google
github.com/cloudflare/utahfs/vendor/google.golang.org/api/transport/http/internal/propagation
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/awserr
github.com/cloudflare/utahfs/vendor/go.opencensus.io/stats/internal
github.com/cloudflare/utahfs/vendor/go.opencensus.io/stats
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/shareddefaults
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/sdkio
github.com/cloudflare/utahfs/vendor/go.opencensus.io/stats/view
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/ini
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/endpoints
github.com/cloudflare/utahfs/vendor/github.com/googleapis/gax-go/v2
github.com/cloudflare/utahfs/vendor/google.golang.org/genproto/googleapis/iam/v1
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/internal
github.com/cloudflare/utahfs/vendor/google.golang.org/api/internal
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/iam
github.com/cloudflare/utahfs/vendor/google.golang.org/api/internal/gensupport
github.com/cloudflare/utahfs/vendor/google.golang.org/api/option
github.com/cloudflare/utahfs/vendor/go.opencensus.io/plugin/ochttp
github.com/cloudflare/utahfs/vendor/google.golang.org/api/option/internaloption
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/credentials
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/client/metadata
github.com/cloudflare/utahfs/vendor/github.com/jmespath/go-jmespath
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/sdkrand
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/credentials/processcreds
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/sdkuri
github.com/cloudflare/utahfs/vendor/github.com/mattn/go-sqlite3
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/awsutil
github.com/cloudflare/utahfs/vendor/google.golang.org/api/transport/http
github.com/cloudflare/utahfs/vendor/google.golang.org/api/storage/v1
github.com/cloudflare/utahfs/vendor/github.com/beorn7/perks/quantile
github.com/cloudflare/utahfs/vendor/github.com/prometheus/client_model/go
github.com/cloudflare/utahfs/vendor/github.com/prometheus/client_golang/prometheus/internal
github.com/cloudflare/utahfs/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/cloudflare/utahfs/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/cloudflare/utahfs/vendor/github.com/prometheus/common/model
github.com/cloudflare/utahfs/vendor/cloud.google.com/go/storage
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws
github.com/cloudflare/utahfs/vendor/github.com/prometheus/common/expfmt
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/request
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/client
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/corehandlers
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/csm
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/rest
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/query/queryutil
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/signer/v4
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/query
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/internal/s3err
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/service/sts
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/defaults
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/private/protocol/restxml
github.com/cloudflare/utahfs/vendor/github.com/prometheus/procfs/internal/fs
github.com/cloudflare/utahfs/vendor/github.com/prometheus/procfs
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/service/s3
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds
github.com/cloudflare/utahfs/vendor/github.com/aws/aws-sdk-go/aws/session
github.com/cloudflare/utahfs/vendor/github.com/prometheus/client_golang/prometheus
github.com/cloudflare/utahfs/vendor/golang.org/x/crypto/blake2b
github.com/cloudflare/utahfs/vendor/golang.org/x/crypto/argon2
github.com/cloudflare/utahfs/vendor/golang.org/x/crypto/hkdf
github.com/cloudflare/utahfs/vendor/github.com/golang/glog
github.com/cloudflare/utahfs/vendor/github.com/google/readahead
github.com/cloudflare/utahfs/vendor/github.com/pquerna/ffjson/fflib/v1/internal
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/fusekernel
github.com/cloudflare/utahfs/vendor/github.com/pquerna/ffjson/fflib/v1
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/fuseops
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer
# github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer
go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer/runtime.go:24:6: missing function body
go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer/runtime.go:29:6: missing function body
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/freelist
github.com/cloudflare/utahfs/vendor/golang.org/x/crypto/ssh/terminal
github.com/cloudflare/utahfs/vendor/github.com/pquerna/ffjson/ffjson
github.com/cloudflare/utahfs/vendor/gopkg.in/kothar/go-backblaze.v0
github.com/cloudflare/utahfs/vendor/gopkg.in/yaml.v2
github.com/cloudflare/utahfs/vendor/github.com/prometheus/client_golang/prometheus/promhttp
github.com/cloudflare/utahfs/persistent
pi@raspberrypi:~ $ ls go/
src
pi@raspberrypi:~ $ 
```

**Comment by Bren2010** [comment]
Hey @AndrewBudd. The issue here is that the FUSE package we use doesn't support 32-bit ARM. I manually applied a patch that supposedly adds it, but I have no way to test. It's on the `arm-support` branch in this repo. Do you mind trying it out and reporting back?

**Comment by dmag** [comment]
I can confirm that the patch does appear to work.

I'm using Go version is 1.13.1 on Rasbian 9.8 (stretch). I can repro the original problem (`go get` on master is was not building).  But with these commands, I get a working binary that runs (and complains about missing a config file, haven't tested further.)
```
cd ~/go/src/github.com/cloudflare/utahfs
git checkout -b 5f88f1e 5f88f1e
go get -v github.com/cloudflare/utahfs/cmd/utahfs-client
~/go/bin/utahfs-client
```

**Comment by AndrewBudd** [comment]
Awesome, will also try shortly.

**Comment by AndrewBudd** [comment]
The build succeeds, however, it is not functional. The same config file works as expected on an x86_64 system

```
pi@raspberrypi:~ $ go/bin/utahfs-client -cfg ./utahfs.yaml -mount ./utahfs
panic: unexpected OutMessage layout

goroutine 1 [running]:
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer.(*OutMessage).Reset(...)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/internal/buffer/out_message.go:67
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse.(*Connection).getOutMessage(0x1d16d90, 0x383e000)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/freelists.go:60 +0x9c
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse.(*Connection).ReadOp(0x1d16d90, 0x1d16d90, 0x0, 0x0, 0x1d065a0, 0xb6d93000, 0x0)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/connection.go:385 +0x74
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse.(*Connection).Init(0x1d16d90, 0x1d16d90, 0x1d2adcc)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/connection.go:121 +0x1c
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse.newConnection(0x9c5588, 0x1c92010, 0x1d15409, 0x6, 0x0, 0x1d26450, 0x0, 0x0, 0x1d15409, 0x6, ...)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/connection.go:108 +0x74
github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse.Mount(0x1d15400, 0xf, 0x9c0778, 0x517a2c0, 0x1d69f90, 0x0, 0x1e416e8, 0x0)
	/home/pi/go/src/github.com/cloudflare/utahfs/vendor/github.com/jacobsa/fuse/mount.go:76 +0x268
main.main()
	/home/pi/go/src/github.com/cloudflare/utahfs/cmd/utahfs-client/main.go:66 +0x488
pi@raspberrypi:~ $ 
```

**Comment by Bren2010** [comment]
Ok, thanks for the update. Give me a bit of time on this then while I figure out a test system and properly add ARM support to our FUSE package.

**Comment by zknill** [comment]
I have a raspberry pi 2 model B, which doesn't have arm64 support

I had to extend the jacobsa/fuse package with arm support

I made changes in the following files:
- https://github.com/jacobsa/fuse/blob/master/internal/buffer/runtime_other.s
- https://github.com/jacobsa/fuse/blob/master/internal/buffer/runtime_go1.8.s

1. added the `arm` build tag in the `+build` comment
2. added the following block ([based on this file](https://github.com/golang/go/blob/d8c6dac/src/os/signal/sig.s))
```
#ifdef GOARCH_arm
#define JMP B
#endif
```

To cross compile `utahfs-server` for my rpi:

1. Installed gcc for armhf arch `gcc-arm-linux-gnueabihf`
2. cross compile `master` branch using: 
```
CC=arm-linux-gnueabihf-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm go build ./cmd/utahfs-server
```

Both the `utahfs-server` and `utahfs-client` seem to be working (but I only tested with tiny files).

I occasionally get this log message, I have not yet worked out what this means / what the impact is.
```
fuse: 2020/06/18 17:11:46 connection.go:486: *fuseops.GetXattrOp error: function not implemented
```

Note: I think if you have an raspberry pi 4 it has arm64 support, so much of this might not be needed.

**Comment by Bren2010** [comment]
@zknill Isn't that the same as the `arm-support` branch on this repo that Andrew said compiled but wasn't functional?

**Comment by zknill** [comment]
@Bren2010 I spent only a short amount of time trying to understand the difference between `master` and `arm-support` (sorry!)

Having looked just now I can see that [this commit from arm-support branch](https://github.com/cloudflare/utahfs/commit/5f88f1e5670616307627aed37bad6b7f31ce15fa) is the only main difference. 

So, yes, you are absolutely right. The changes I made are the same as the `arm-support` branch.

I can't speak to why Andrew's setup didn't work. I did a cross compile, I don't know if that will have made a difference (?)

**Comment by AndrewBudd** [comment]
To be clear, are you able to make it work?

**Comment by Bren2010** [comment]
This should be resolved by https://github.com/jacobsa/fuse/pull/85 although I'll give the project maintainer there some time to review my PR before recommending people use it seriously.

**Comment by AndrewBudd** [comment]
can confirm, now tested and working. Nice!
